apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
        - name: authapi
          image: europe-west2-docker.pkg.dev/lucid-vector-443917-b3/docker-repo/authapi:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: authapi
spec:
  selector:
    app: authapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
