apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  mysql-username: dXNlcg==  # Base64-encoded 'user'
  mysql-root-username: cm9vdA==  # Base64-encoded 'root'
  mysql-password: c2VjcmV0  # Base64-encoded 'secret'
  mysql-root-password: dmVyeXNlY3JldA==  # Base64-encoded 'verysecret'
