apiVersion: apps/v1
kind: Deployment
metadata:
  name: contentapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contentapi
  template:
    metadata:
      labels:
        app: contentapi
    spec:
      containers:
        - name: contentapi
          image: europe-west2-docker.pkg.dev/lucid-vector-443917-b3/docker-repo/contentapi:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: contentapi
spec:
  selector:
    app: contentapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
