name: User Api CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "userApi/**"
      - "build.gradle"
      - "settings.gradle"
  pull_request:
    branches: [ "main" ]
    paths:
      - "userApi/**"
      - "build.gradle"
      - "settings.gradle"

jobs:
  build-user-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.9'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build User Api with Gradle Wrapper
        run: ./gradlew :userApi:build

